# .github/workflows/build.yml
name: "Unit tests"

on: [ push ]

jobs:

    build:
        name:    "PHP ${{ matrix.php-version }}"
        runs-on: ubuntu-22.04

        strategy:
            matrix:
                include:
                    -   php-version: "7.1"
                    -   php-version: "7.2"
                    -   php-version: "7.3"
                    -   php-version: "7.4"
                    -   php-version: "8.0"
                    -   php-version: "8.1"
                    -   php-version: "8.2"
                    -   php-version: "8.3"

        steps:
            -   name: "Checkout"
                uses: actions/checkout@v4

            -   name: "Environment"
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php-version }}"
                    coverage:    "xdebug"

            -   name: "Dependencies"
                run:  |
                      php --version
                      composer --version
                      COMPOSER_MEMORY_LIMIT=-1 composer update

            -   name: "Application"
                run:  |
                      mkdir -p build/logs
                      vendor/bin/phpunit --coverage-clover build/logs/clover.xml

            -   name: "Coverage"
                env:
                    COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    COVERALLS_FLAG_NAME:  php-${{ matrix.php-version }}
                    COVERALLS_PARALLEL:   true
                run:  |
                      wget -c -nc --retry-connrefused --tries=0 https://github.com/php-coveralls/php-coveralls/releases/download/v2.5.3/php-coveralls.phar -O coveralls.phar
                      chmod +x coveralls.phar
                      php coveralls.phar --version
                      php coveralls.phar --coverage_clover=build/logs/clover.xml -v

    coverage:
        name:    "Coverage"
        runs-on: ubuntu-22.04
        needs:   "build"
        if:      always()

        steps:
            -   name: "Coverage"
                uses: coverallsapp/github-action@v2
                with:
                    github-token:      ${{ secrets.GITHUB_TOKEN }}
                    parallel-finished: true
